version: "3.9"  # optional since v1.27.0
services:
  loc_test_1:
    image: ngspice-batch-runner:latest
    environment:
      AWS_BATCH_JOB_ARRAY_INDEX: 0
      NGSPICE_TEST: sar_adc_sine_test.spice
      NGSPICE_TEST_PATH: xschem/simulation
    volumes: 
     - ./docker_volume:/foss/designs:rw
  loc_test_2:
    image: ngspice-batch-runner:latest
    environment:
      AWS_BATCH_JOB_ARRAY_INDEX: 1
      NGSPICE_TEST: sar_adc_sine_test.spice
      NGSPICE_TEST_PATH: xschem/simulation
    volumes: 
     - ./docker_volume:/foss/designs:rw

